services:
  - type: web
    name: your-app-name
    env: ruby
    buildCommand: "bundle install && yarn install && bundle exec rake assets:precompile"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: GOOGLE_MAPS_API_KEY
        sync: false
